"""Tests for the alert-only indicator generator.

The most important behaviour under test is the REFUSAL. A generator that
silently emits something plausible for a strategy it cannot faithfully convert
is worse than one that does nothing, because the output looks finished.
"""
import tempfile
import unittest
from pathlib import Path

from tests.helpers import SCRIPTS_DIR, codes, lint_text, run_script  # noqa: F401

import pine_fmt
import strategy_to_indicator as s2i

SIGNAL_ONLY = '''\
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
//@version=6
strategy("Cross", "CX", overlay=true, default_qty_type=strategy.percent_of_equity,
     default_qty_value=10, initial_capital=10000, commission_type=strategy.commission.percent,
     commission_value=0.05, slippage=1)
float fastMa = ta.ema(close, 10)
float slowMa = ta.ema(close, 30)
bool goLong = ta.crossover(fastMa, slowMa)
bool goFlat = ta.crossunder(fastMa, slowMa)
strategy.risk.max_drawdown(20, strategy.percent_of_equity)
if goLong
    strategy.entry("Long", strategy.long)
if goFlat
    strategy.close("Long")
plot(fastMa, title="Fast MA")
'''

READS_POSITION = SIGNAL_ONLY.replace(
    "if goFlat\n    strategy.close(\"Long\")",
    "if goFlat and strategy.position_size > 0\n    strategy.close(\"Long\")")


class TestConversion(unittest.TestCase):
    def convert(self, text, force=False):
        return s2i.convert(text, "test.pine", force)

    def test_declaration_becomes_an_indicator(self):
        out, _notes, _blockers = self.convert(SIGNAL_ONLY)
        self.assertIn('indicator("Cross", "CX", overlay=true)', out)
        self.assertNotIn("strategy(", out)

    def test_backtest_only_arguments_are_dropped(self):
        out, notes, _blockers = self.convert(SIGNAL_ONLY)
        for arg in ("default_qty_type", "initial_capital", "commission_value", "slippage"):
            self.assertNotIn(arg, out)
        self.assertTrue(any("dropped" in n for n in notes))

    def test_order_calls_become_alerts_that_keep_their_id(self):
        out, _notes, _blockers = self.convert(SIGNAL_ONLY)
        self.assertIn('alert("ENTRY LONG Long @ "', out)
        self.assertIn('alert("CLOSE Long @ "', out)
        self.assertNotIn("strategy.entry(", out)
        self.assertNotIn("strategy.close(", out)

    def test_alerts_fire_on_bar_close(self):
        """A signal can form mid-bar and vanish. The generated alert must not
        inherit a frequency that fires on one that never happened."""
        out, _notes, _blockers = self.convert(SIGNAL_ONLY)
        self.assertIn("alert.freq_once_per_bar_close", out)

    def test_risk_guards_are_commented_out(self):
        out, notes, _blockers = self.convert(SIGNAL_ONLY)
        self.assertIn("// [removed by strategy_to_indicator] strategy.risk.max_drawdown", out)
        self.assertTrue(any("risk guard" in n for n in notes))

    def test_the_wrapped_alert_keeps_the_enclosing_indent(self):
        """A continuation dedented to column 0 would read as leaving the `if`
        block — Pine's indentation is structural, so this is a correctness
        requirement, not a formatting preference."""
        out, _notes, _blockers = self.convert(SIGNAL_ONLY)
        lines = out.splitlines()
        idx = next(i for i, l in enumerate(lines) if "ENTRY LONG" in l)
        self.assertTrue(lines[idx].startswith("    "))
        self.assertTrue(lines[idx + 1].startswith("     "))

    def test_generated_output_lints_and_formats_clean(self):
        out, _notes, _blockers = self.convert(SIGNAL_ONLY)
        result = lint_text(out)
        self.assertEqual([], [f.msg for f in result.findings])
        self.assertEqual(out, pine_fmt.format_text(out))

    def test_output_says_plainly_that_it_is_not_a_backtest(self):
        out, _notes, _blockers = self.convert(SIGNAL_ONLY)
        self.assertIn("IT IS NOT A BACKTEST", out)
        self.assertIn("GENERATED by scripts/strategy_to_indicator.py", out)

    def test_license_header_stays_on_the_first_line(self):
        out, _notes, _blockers = self.convert(SIGNAL_ONLY)
        self.assertTrue(out.splitlines()[0].startswith("// This source code is subject"))


class TestRefusal(unittest.TestCase):
    def test_position_state_blocks_conversion(self):
        out, _notes, blockers = s2i.convert(READS_POSITION, "test.pine", force=False)
        self.assertIsNone(out)
        self.assertTrue(blockers)
        self.assertIn("strategy.position_size", blockers[0][1])

    def test_force_emits_a_draft_with_every_blocker_marked(self):
        out, _notes, blockers = s2i.convert(READS_POSITION, "test.pine", force=True)
        self.assertIsNotNone(out)
        self.assertEqual(len(blockers), out.count("// UNCONVERTED:"))

    def test_cli_exits_1_and_names_the_blocking_lines(self):
        with tempfile.TemporaryDirectory() as td:
            pine = Path(td) / "s.pine"
            pine.write_text(READS_POSITION, encoding="utf-8")
            proc = run_script("strategy_to_indicator.py", pine)
            self.assertEqual(1, proc.returncode)
            self.assertIn("strategy.position_size", proc.stdout)
            self.assertIn("--force", proc.stdout)

    def test_the_repo_strategy_is_correctly_refused(self):
        """reversal_pro_strategy reads position size, average price, open trades
        and equity. It genuinely cannot be converted, and the tool saying so is
        the correct result — not a gap to work around."""
        from tests.helpers import REPO_ROOT
        source = (REPO_ROOT / "strategies" / "reversal_pro_strategy" / "src"
                  / "reversal_pro_strategy.pine")
        _out, _notes, blockers = s2i.convert(
            source.read_text(encoding="utf-8"), source.name, force=False)
        self.assertTrue(blockers)
        tokens = {token for _ln, token, _src in blockers}
        self.assertIn("strategy.position_size", tokens)


if __name__ == "__main__":
    unittest.main()
