#!/usr/bin/env python3
"""
build_index.py - Generate the repo's project registry and the file-tree block.

With four projects a hand-maintained list is a mild annoyance. With ten it is
wrong, because updating it is a step nobody remembers at the moment it matters.
This repo already proved the point: the README's tree block was missing four
scripts and four reference docs by the time anyone looked.

It writes into marked regions, so the prose around them stays hand-written:

    <!-- BEGIN GENERATED: projects -->
    ...replaced...
    <!-- END GENERATED: projects -->

Regions: `projects` (the registry table) and `tree` (the file tree).

Usage:
    python3 build_index.py            # rewrite the marked regions
    python3 build_index.py --check    # exit 1 if anything is out of date
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import pine_lint  # noqa: E402

# indicators/ and strategies/ are deliberately absent: they are private trading
# work (see .gitignore) and the generated README must never list them, on this
# machine or any other. Listing a project whose files are not in the repo would
# also produce a README full of broken links.
PROJECT_PARENTS = ["libraries"]
TARGETS = ["README.md", "SKILL.md"]

TREE_ROOTS = ["scripts", "references", "references/snippets", "assets/templates"]


def region_re(name):
    return re.compile(
        r'(<!-- BEGIN GENERATED: ' + re.escape(name) + r' -->\n)(.*?)(<!-- END GENERATED: '
        + re.escape(name) + r' -->)', re.DOTALL)


def projects():
    for parent in PROJECT_PARENTS:
        base = ROOT / parent
        if not base.is_dir():
            continue
        for child in sorted(base.iterdir()):
            version_file = child / "version.json"
            if not version_file.exists():
                continue
            meta = json.loads(version_file.read_text(encoding="utf-8"))
            source = child / "src" / f"{meta['name']}.pine"
            yield parent, child, meta, source


def first_changelog_note(changelog):
    """The first bullet under the newest released heading — a one-line summary
    of what the project most recently became."""
    if not changelog.exists():
        return "—"
    seen_release = False
    for line in changelog.read_text(encoding="utf-8").splitlines():
        if re.match(r'^## \[\d+\.\d+\.\d+\]', line):
            seen_release = True
            continue
        if seen_release and line.startswith("- "):
            return line[2:].strip()
        if seen_release and line.startswith("### "):
            continue
        if seen_release and line.startswith("## "):
            break
    return "—"


def render_projects():
    rows = [
        "| Project | Kind | Version | Lines | Lint | What it is |",
        "|---|---|---|---|---|---|",
    ]
    for parent, child, meta, source in projects():
        if not source.exists():
            continue
        text = source.read_text(encoding="utf-8")
        result = pine_lint.lint_file(str(source), dict(pine_lint.DEFAULT_CONFIG))
        errors = len(result.by_severity("error"))
        warnings = len(result.by_severity("warning"))
        notes = len(result.by_severity("info"))
        if errors or warnings:
            status = f"{errors}E {warnings}W"
        elif notes:
            status = f"clean ({notes} note{'s' if notes > 1 else ''})"
        else:
            status = "clean"
        summary = first_changelog_note(child / "CHANGELOG.md")
        if len(summary) > 90:
            summary = summary[:87] + "…"
        rel = f"{parent}/{child.name}"
        rows.append(
            f"| [`{child.name}`]({rel}/) | {meta.get('kind', '—')} | "
            f"`{meta.get('version', '?')}` | {len(text.splitlines())} | {status} | "
            f"{summary.replace('|', chr(92) + '|')} |")
    rows.append("")
    rows.append(f"*{len(rows) - 3} project(s). Generated by `scripts/build_index.py`.*")
    return "\n".join(rows) + "\n"


def render_tree():
    lines = ["```", "PineScript-Skill/"]
    project_rows = [(f"├── {parent}/{child.name}/",
                     f"# v{meta.get('version', '?')} ({meta.get('kind', '?')})")
                    for parent, child, meta, _src in projects()]
    # One column for every comment, computed from the longest path — a fixed
    # width would go ragged the moment a project with a longer name appears.
    width = max((len(path) for path, _c in project_rows), default=0) + 2
    for path, comment in project_rows:
        lines.append(f"{path.ljust(width)}{comment}")

    for root in TREE_ROOTS:
        base = ROOT / root
        if not base.is_dir():
            continue
        lines.append(f"├── {root}/")
        entries = sorted(p for p in base.iterdir()
                         if p.is_file() and p.suffix in (".py", ".md", ".pine"))
        for i, entry in enumerate(entries):
            branch = "└──" if i == len(entries) - 1 else "├──"
            lines.append(f"│   {branch} {entry.name}")

    lines.append("├── tests/")
    tests = sorted(p.name for p in (ROOT / "tests").glob("test_*.py"))
    for i, entry in enumerate(tests):
        branch = "└──" if i == len(tests) - 1 else "├──"
        lines.append(f"│   {branch} {entry}")
    lines.append("└── .github/workflows/ci.yml")
    lines.append("```")
    return "\n".join(lines) + "\n"


RENDERERS = {"projects": render_projects, "tree": render_tree}


def apply(text):
    """Returns (new_text, [region names found])."""
    found = []
    for name, render in RENDERERS.items():
        pattern = region_re(name)
        if not pattern.search(text):
            continue
        found.append(name)
        text = pattern.sub(lambda m: m.group(1) + render() + m.group(3), text)
    return text, found


def main():
    pine_lint.make_output_encoding_safe()
    parser = argparse.ArgumentParser(description="Generate the repo's project registry.")
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if a generated region is out of date")
    args = parser.parse_args()

    stale = []
    for rel in TARGETS:
        path = ROOT / rel
        if not path.exists():
            continue
        original = path.read_text(encoding="utf-8")
        updated, found = apply(original)
        if not found:
            continue
        if updated == original:
            print(f"{rel}: up to date ({', '.join(found)})")
            continue
        if args.check:
            stale.append(rel)
            print(f"{rel}: OUT OF DATE ({', '.join(found)})")
        else:
            path.write_text(updated, encoding="utf-8")
            print(f"{rel}: regenerated ({', '.join(found)})")

    if args.check and stale:
        print("\nRun: python3 scripts/build_index.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
