#!/usr/bin/env python3
"""
strategy_to_indicator.py - Generate an alert-only indicator from a strategy.

A strategy backtests. An indicator alerts. Traders routinely want both from one
set of signals, and the usual answer is a second file maintained by hand, which
drifts — the same problem the SHARED SCORING ENGINE markers exist to contain.

What it converts, mechanically and safely:

    strategy(...)              -> indicator(...), strategy-only arguments dropped
    strategy.entry/exit/close  -> alert() carrying the same id and direction
    strategy.risk.*            -> commented out; an indicator has no account

WHAT IT REFUSES TO CONVERT, and why that is the point:

An indicator has no position. Any script that READS live position state —
strategy.position_size, strategy.position_avg_price, strategy.opentrades,
strategy.equity and their relatives — is asking a question an indicator cannot
answer. There is no honest mechanical rewrite: emulating a position tracker
would mean silently reimplementing the order engine and producing alerts that
disagree with the backtest they claim to mirror.

So the tool stops and names every blocking line. That output is the useful
result, not a failure to work around. `--force` emits anyway with each blocker
marked `// UNCONVERTED:` — for a human to finish, never to ship as-is.

Usage:
    python3 strategy_to_indicator.py strategies/my_strategy
    python3 strategy_to_indicator.py FILE.pine --out signals.pine
    python3 strategy_to_indicator.py FILE.pine --force
"""
import argparse
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import pine_lint  # noqa: E402

# Arguments that only mean something to the backtest engine.
STRATEGY_ONLY_ARGS = {
    "default_qty_type", "default_qty_value", "initial_capital", "currency",
    "commission_type", "commission_value", "slippage", "pyramiding",
    "calc_on_order_fills", "calc_on_every_tick", "process_orders_on_close",
    "close_entries_rule", "margin_long", "margin_short", "backtest_fill_limits_assumption",
    "risk_free_rate", "fill_orders_on_standard_ohlc", "use_bar_magnifier",
}

ORDER_CALL_RE = re.compile(
    r'(?<![.\w])strategy\s*\.\s*(entry|order|exit|close|close_all|cancel|cancel_all)\s*\(')
RISK_CALL_RE = re.compile(r'(?<![.\w])strategy\s*\.\s*risk\s*\.\s*\w+\s*\(')

# Reading any of these is what makes a script unconvertible.
POSITION_STATE_RE = re.compile(
    r'(?<![.\w])strategy\s*\.\s*('
    r'position_size|position_avg_price|position_entry_name|'
    r'opentrades|closedtrades|equity|netprofit|grossprofit|grossloss|'
    r'wintrades|losstrades|eventrades|openprofit|max_drawdown|max_runup|'
    r'account_currency|initial_capital|margin_liquidation_price|'
    r'avg_trade|avg_winning_trade|avg_losing_trade)\b')

GENERATED_HEADER = """// ===========================================================================
// GENERATED by scripts/strategy_to_indicator.py from {source}
//
// This is the alert-only view of that strategy: the same signals, no order
// engine. Every strategy.entry/exit/close has become an alert() carrying the
// id and direction the order would have used.
//
// IT IS NOT A BACKTEST AND CANNOT BE ONE. There is no position here, so
// nothing sizes a trade, tracks an average price, or applies a risk guard.
// Anything the strategy did with account state was dropped, and where that
// could not be done safely the generator stopped instead.
//
// Regenerate rather than edit. Edits here are lost on the next run.
// ===========================================================================
"""


def rewrite_declaration(text):
    """strategy(...) -> indicator(...), dropping backtest-only arguments."""
    idx = text.find("strategy(")
    if idx == -1:
        idx = text.find("strategy (")
        if idx == -1:
            return text, ["no strategy() declaration found"]
    arg_text = pine_lint.call_arg_text(text[idx:], "strategy(")
    if arg_text is None:
        return text, ["strategy() declaration is not closed"]

    kept, dropped = [], []
    for arg in pine_lint.split_top_level_args(arg_text):
        name = arg.split("=", 1)[0].strip()
        if name in STRATEGY_ONLY_ARGS:
            dropped.append(name)
        else:
            kept.append(arg)

    end = idx + len("strategy(") + len(arg_text) + 1
    replacement = "indicator(" + ", ".join(kept) + ")"
    note = (f"declaration: dropped {len(dropped)} backtest-only argument(s) "
            f"({', '.join(dropped)})") if dropped else "declaration: no arguments dropped"
    return text[:idx] + replacement + text[end:], [note]


def _order_alert(kind, arg_text):
    """Builds the alert() that replaces one order call, preserving its id."""
    args = pine_lint.split_top_level_args(arg_text)
    positional = pine_lint.positional_args(args)
    order_id = positional[0].strip() if positional else '"' + kind + '"'
    direction = ""
    for a in positional[1:]:
        if "strategy.long" in a:
            direction = " LONG"
            break
        if "strategy.short" in a:
            direction = " SHORT"
            break
    label = kind.upper().replace("_", " ")
    # A literal id folds straight into the message. Wrapping it in
    # str.tostring() would compile, but generated code that is more convoluted
    # than the code a human would write is code nobody will trust or maintain.
    if order_id.startswith('"') and order_id.endswith('"'):
        head = f'"{label}{direction} {order_id[1:-1]} @ "'
    else:
        head = f'"{label}{direction} " + str.tostring({order_id}) + " @ "'
    return (f'alert({head} + str.tostring(close, format.mintick),\n'
            f'ALERTINDENT     alert.freq_once_per_bar_close)')


def convert_line(raw):
    """Returns (new_line, note) for one physical line."""
    code = pine_lint.strip_comments_only(raw)

    if RISK_CALL_RE.search(code):
        indent = raw[:len(raw) - len(raw.lstrip())]
        return (f"{indent}// [removed by strategy_to_indicator] {raw.strip()}",
                "risk guard removed — an indicator has no account to guard")

    m = ORDER_CALL_RE.search(code)
    if not m:
        return raw, None
    kind = m.group(1)
    call_start = m.start()
    arg_text = pine_lint.call_arg_text(code[call_start:], code[call_start:m.end()])
    if arg_text is None:
        return raw, None
    indent = raw[:len(raw) - len(raw.lstrip())]
    # The alert is emitted wrapped, so the continuation gets the caller's indent
    # too — otherwise a call inside an `if` block dedents to column 0 and Pine
    # reads it as leaving the block.
    body = _order_alert(kind, arg_text).replace("ALERTINDENT", indent)
    return indent + body, f"strategy.{kind}() -> alert()"


def find_blockers(lines):
    """Lines reading live position state, which an indicator does not have."""
    blockers = []
    for i, raw in enumerate(lines):
        code = pine_lint.strip_comments_only(raw)
        m = POSITION_STATE_RE.search(code)
        if m:
            blockers.append((i + 1, m.group(0), raw.strip()))
    return blockers


def convert(text, source_name, force):
    """Returns (converted_text_or_None, notes, blockers)."""
    lines = text.splitlines()
    blockers = find_blockers(lines)
    if blockers and not force:
        return None, [], blockers

    text, notes = rewrite_declaration(text)
    out = []
    for raw in text.splitlines():
        new_line, note = convert_line(raw)
        out.append(new_line)
        if note and note not in notes:
            notes.append(note)

    if force and blockers:
        blocked_lines = {ln for ln, _tok, _src in blockers}
        for ln in blocked_lines:
            if ln - 1 < len(out):
                indent = out[ln - 1][:len(out[ln - 1]) - len(out[ln - 1].lstrip())]
                out[ln - 1] = (f"{indent}// UNCONVERTED: reads live position state\n"
                               + out[ln - 1])

    # The header goes after the license line so the license stays first.
    body = "\n".join(out)
    header = GENERATED_HEADER.format(source=source_name)
    first_newline = body.find("\n")
    if body.startswith("//") and first_newline != -1:
        body = body[:first_newline + 1] + header + body[first_newline + 1:]
    else:
        body = header + body
    return body + "\n", notes, blockers


def resolve_source(target):
    path = Path(target)
    if path.is_file():
        return path
    if path.is_dir():
        version = path / "version.json"
        if version.exists():
            name = json.loads(version.read_text(encoding="utf-8"))["name"]
            candidate = path / "src" / f"{name}.pine"
            if candidate.exists():
                return candidate
        candidates = sorted((path / "src").glob("*.pine")) if (path / "src").is_dir() else []
        if len(candidates) == 1:
            return candidates[0]
    return None


def main():
    pine_lint.make_output_encoding_safe()
    parser = argparse.ArgumentParser(
        description="Generate an alert-only indicator from a Pine strategy.")
    parser.add_argument("target", help="A strategy .pine file, or its project directory")
    parser.add_argument("--out", default=None,
                        help="Output path (default: <project>/generated/<name>_signals.pine)")
    parser.add_argument("--force", action="store_true",
                        help="Emit even when position state blocks a clean conversion")
    args = parser.parse_args()

    source = resolve_source(args.target)
    if source is None:
        print(f"error: no .pine source found at {args.target}", file=sys.stderr)
        return 1

    text = source.read_text(encoding="utf-8")
    if "strategy(" not in text.replace(" ", ""):
        print(f"error: {source} is not a strategy.", file=sys.stderr)
        return 1

    converted, notes, blockers = convert(text, source.name, args.force)

    if blockers and not args.force:
        print(f"Cannot convert {source} without losing meaning.\n")
        print("These lines read live position state, which an indicator does not have.")
        print("There is no honest mechanical rewrite: emulating a position tracker would")
        print("silently reimplement the order engine and produce alerts that disagree")
        print("with the backtest they claim to mirror.\n")
        for line_no, token, src in blockers:
            print(f"  {source.name}:{line_no}: {token}")
            print(f"      {src[:100]}")
        print(f"\n{len(blockers)} blocking line(s). Options:")
        print("  - Restructure the strategy so the signal is computed independently of")
        print("    position state, then convert the signal half.")
        print("  - Run again with --force to emit a draft with each blocker marked")
        print("    // UNCONVERTED: for a human to finish. Do not ship that as-is.")
        return 1

    if args.out:
        out_path = Path(args.out)
    else:
        project = source.parent.parent
        out_path = project / "generated" / f"{source.stem}_signals.pine"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(converted, encoding="utf-8")

    print(f"Wrote {out_path}")
    for note in notes:
        print(f"  - {note}")
    if blockers:
        print(f"\n  WARNING: {len(blockers)} line(s) marked // UNCONVERTED. This draft")
        print("  is not correct until a human resolves every one of them.")
    print("\nLint it before using it:")
    print(f"  python3 scripts/pine_lint.py {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
